# logger config
logging:
    level:
        com.jiang: debug

mybatis-plus:
  # 扫描mapper.xml
  mapper-locations: classpath:/mapper/*/*Mapper.xml
server:
  port: 80
  servlet:
    context-path: /

# application